In [ ]:
## code to extract smiles and its compound_id from "top500_for_docking.csv" data for ADMET profiling.....
## Generated smi formats to load files on swissADME and pkCSM and ADMETlab3.0 webservers for ADMET profiling of top 500 compounds.
## Extrated all 3 results in csv file

In [1]:
import pandas as pd

# Read both CSV files
df = pd.read_csv('/content/top500_for_docking.csv')
df.head()

,Common_Name,SMILES,MolWt,LogP,NumHDonors,NumHAcceptors,NumRings,NumRotatableBonds,NumHeavyAtoms,NumHeteroatoms,NumAromaticRings,TPSA,FractionCSP3,MorganFingerprint,Predicted_Prob,Predicted_Activity
0,Ceralifimod,CCCc1ccc(COc2ccc3c(c2)CCC(CN2CC(C(=O)O)C2)=C3C...,435.564,4.96280,1.0,4.0,4.0,9.0,32.0,5.0,2.0,59.00,0.444444,[0 0 0 ... 1 0 0],1.0,1
1,Ponesimod,CCC/N=C1\S/C(=C\c2ccc(OC[C@H](O)CO)c(Cl)c2)C(=...,460.983,4.26732,2.0,6.0,3.0,8.0,31.0,8.0,2.0,82.36,0.304348,[0 1 0 ... 0 0 0],1.0,1
2,Etrasimod,O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...,457.492,6.92780,2.0,2.0,5.0,6.0,33.0,7.0,3.0,62.32,0.423077,[0 0 0 ... 0 0 0],1.0,1
3,Siponimod,CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...,516.604,6.77270,1.0,4.0,4.0,9.0,37.0,8.0,2.0,62.13,0.517241,[0 0 1 ... 1 0 0],1.0,1
4,Ozanimod,CC(C)Oc1ccc(-c2nc(-c3cccc4c3CC[C@@H]4NCCO)no2)...,404.470,3.63168,2.0,7.0,4.0,7.0,30.0,7.0,3.0,104.20,0.347826,[0 1 0 ... 0 0 0],1.0,1

In [2]:
data = pd.read_csv('/content/docking_summary.csv')
data.head()

                                              Ligand  Best_Affinity_(kcal/mol)
0                                    93_Adomeglivant                   -11.314
1  374_4__6____4_METHYLCYCLOHEXYL_AMINO_METHYL__1...                   -11.268
2                                        3_Etrasimod                   -11.070
3                                      348_Vamotinib                   -10.989
4                                        4_Siponimod                   -10.921

In [3]:
# Extract serial number from the 'Ligand' column in the second file
def extract_serial_number(ligand_name):
    try:
        # Split by underscore and take the first part as serial number
        return int(ligand_name.split('_')[0])
    except:
        return None

# Apply the function to extract serial numbers
data['Serial_Number'] = data['Ligand'].apply(extract_serial_number)
data.head()

,Ligand,Best_Affinity_(kcal/mol),Serial_Number
0,93_Adomeglivant,-11.314,93
1,374_4__6____4_METHYLCYCLOHEXYL_AMINO_METHYL__1...,-11.268,374
2,3_Etrasimod,-11.070,3
3,348_Vamotinib,-10.989,348
4,4_Siponimod,-10.921,4

In [4]:
# Create mapping dictionaries from the first file
name_mapping = {}
smiles_mapping = {}

for idx, row in df.iterrows():
    serial_num = idx + 1  # Assuming position in first file corresponds to serial number
    name_mapping[serial_num] = row['Common_Name']
    smiles_mapping[serial_num] = row['SMILES']

# Map the Common_Name and SMILES to the second file using serial numbers
data['Common_Name'] = data['Serial_Number'].map(name_mapping)
data['SMILES'] = data['Serial_Number'].map(smiles_mapping)
data.head()

,Ligand,Best_Affinity_(kcal/mol),Serial_Number,Common_Name,SMILES
0,93_Adomeglivant,-11.314,93,Adomeglivant,Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...
1,374_4__6____4_METHYLCYCLOHEXYL_AMINO_METHYL__1...,-11.268,374,"4-(6-{[(4-METHYLCYCLOHEXYL)AMINO]METHYL}-1,4-D...",C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...
2,3_Etrasimod,-11.070,3,Etrasimod,O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...
3,348_Vamotinib,-10.989,348,Vamotinib,Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...
4,4_Siponimod,-10.921,4,Siponimod,CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...

In [5]:
# Select and reorder the columns you want in the final output
final_df = data[['Serial_Number', 'Common_Name', 'SMILES', 'Ligand', 'Best_Affinity_(kcal/mol)']]
final_df.head()

,Serial_Number,Common_Name,SMILES,Ligand,Best_Affinity_(kcal/mol)
0,93,Adomeglivant,Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...,93_Adomeglivant,-11.314
1,374,"4-(6-{[(4-METHYLCYCLOHEXYL)AMINO]METHYL}-1,4-D...",C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...,374_4__6____4_METHYLCYCLOHEXYL_AMINO_METHYL__1...,-11.268
2,3,Etrasimod,O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...,3_Etrasimod,-11.070
3,348,Vamotinib,Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...,348_Vamotinib,-10.989
4,4,Siponimod,CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...,4_Siponimod,-10.921

In [6]:
# Filter for strong binders (affinity ≤ -7.0)
filtered_df = final_df[final_df['Best_Affinity_(kcal/mol)'] <= -7.0]
filtered_df.head()

,Serial_Number,Common_Name,SMILES,Ligand,Best_Affinity_(kcal/mol)
0,93,Adomeglivant,Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...,93_Adomeglivant,-11.314
1,374,"4-(6-{[(4-METHYLCYCLOHEXYL)AMINO]METHYL}-1,4-D...",C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...,374_4__6____4_METHYLCYCLOHEXYL_AMINO_METHYL__1...,-11.268
2,3,Etrasimod,O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...,3_Etrasimod,-11.070
3,348,Vamotinib,Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...,348_Vamotinib,-10.989
4,4,Siponimod,CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...,4_Siponimod,-10.921

In [7]:
# Keep only SMILES, Common_Name and binding hits
result = filtered_df[['SMILES','Common_Name', 'Best_Affinity_(kcal/mol)']]
result.head()

,SMILES,Common_Name,Best_Affinity_(kcal/mol)
0,Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...,Adomeglivant,-11.314
1,C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...,"4-(6-{[(4-METHYLCYCLOHEXYL)AMINO]METHYL}-1,4-D...",-11.268
2,O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...,Etrasimod,-11.070
3,Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...,Vamotinib,-10.989
4,CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...,Siponimod,-10.921

In [8]:
# save as csv
result.to_csv('filtered_strong_binders.csv', index=False)

In [9]:
## Fetch CID number from pubchem

!pip install pubchempy

Collecting pubchempy
  Downloading pubchempy-1.0.5-py3-none-any.whl.metadata (4.3 kB)
Downloading pubchempy-1.0.5-py3-none-any.whl (21 kB)
Installing collected packages: pubchempy
Successfully installed pubchempy-1.0.5

In [10]:

import pubchempy as pcp
import pandas as pd

# Load your filtered dataframe
df = pd.read_csv('/content/filtered_strong_binders.csv')

# Function to get CID for a SMILES
def get_cid(smiles):
    try:
        compounds = pcp.get_compounds(smiles, 'smiles')
        if compounds:
            return compounds[0].cid
        else:
            return None
    except:
        return None

# Apply function to your dataframe
df['CID'] = df['SMILES'].apply(get_cid)

# Save new CSV with CIDs
df.to_csv('/content/filtered_strong_binders_with_CID.csv', index=False)

# Check results
print(df.head())

                                              SMILES  \
0  Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...
1  C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...
2  O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...
3  Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...
4  CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...

                                         Common_Name  \
0                                       Adomeglivant
1  4-(6-{[(4-METHYLCYCLOHEXYL)AMINO]METHYL}-1,4-D...
2                                          Etrasimod
3                                          Vamotinib
4                                          Siponimod

   Best_Affinity_(kcal/mol)       CID
0                   -11.314  91933867
1                   -11.268   9844011
2                   -11.070  44623998
3                   -10.989  71475839
4                   -10.921  44599207

In [11]:
df.head()

,SMILES,Common_Name,Best_Affinity_(kcal/mol),CID
0,Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...,Adomeglivant,-11.314,91933867
1,C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...,"4-(6-{[(4-METHYLCYCLOHEXYL)AMINO]METHYL}-1,4-D...",-11.268,9844011
2,O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...,Etrasimod,-11.070,44623998
3,Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...,Vamotinib,-10.989,71475839
4,CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...,Siponimod,-10.921,44599207

In [12]:
len(df)

171

In [13]:
# ## For SwissADME save as "'swissadme_batch.smi' file

# dataframe with SMILES and CID.
# For SwissADME, need to export this into the .smi format.


# Save SMILES + CID into .smi file for SwissADME
df[['SMILES', 'CID']].to_csv(
    'swissadme_batch.smi',
    sep='\t',   # tab separated
    header=False,
    index=False
)

df.head()

,SMILES,Common_Name,Best_Affinity_(kcal/mol),CID
0,Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...,Adomeglivant,-11.314,91933867
1,C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...,"4-(6-{[(4-METHYLCYCLOHEXYL)AMINO]METHYL}-1,4-D...",-11.268,9844011
2,O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...,Etrasimod,-11.070,44623998
3,Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...,Vamotinib,-10.989,71475839
4,CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...,Siponimod,-10.921,44599207

In [14]:
swiss = pd.read_csv('/content/swissadme_batch.smi', sep='\t', header=None)
swiss.head()

                                                   0         1
0  Cc1cc(O[C@@H](CCC(F)(F)F)c2ccc(C(=O)NCCC(=O)O)...  91933867
1  C[C@H]1CC[C@@H](NCc2ccc3c(c2)Cc2c(-c4ccc(C(=O)...   9844011
2  O=C(O)C[C@H]1CCc2c1[nH]c1ccc(OCc3ccc(C4CCCC4)c...  44623998
3  Cc1ccc(C(=O)Nc2ccc(CN3CCN(C)CC3)c(C(F)(F)F)c2)...  71475839
4  CCc1cc(/C(C)=N/OCc2ccc(C3CCCCC3)c(C(F)(F)F)c2)...  44599207

In [16]:
# ## For pkCSM

# # Generate pkCSM .smi file
# import math
# batch_size = 100
# num_batches = math.ceil(len(df) / batch_size)

# for i in range(num_batches):
#     start = i * batch_size
#     end = start + batch_size
#     batch_df = df.iloc[start:end][['SMILES', 'CID']]

#     filename = f"pkcsm_batch{i+1}.smi"
#     with open(filename, 'w') as f:
#         for idx, row in batch_df.iterrows():
#             f.write(f"{row['SMILES']} {row['CID']}\n")
#     print(f"Saved {filename} with {len(batch_df)} compounds")

In [17]:
# pkCSM1 = pd.read_csv('/content/pkcsm_batch1.smi', sep='\t', header=None)
# pkCSM1.head()

In [15]:
### For ADMETlab

# For ADMETlab 2.0, it’s very similar to SwissADME — it accepts a .smi file with SMILES and a name or ID.
# Generate ADMETlab CSV batch file
df[['SMILES', 'CID']].to_csv(
    'admetlab_batch.csv',
    index=False,
    header=['SMILES', 'CID']
)

print("ADMETlab batch CSV created:", 'admetlab_batch.csv')

ADMETlab batch CSV created: admetlab_batch.csv